# Generated by Django 5.1.5 on 2025-02-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dano', models.IntegerField(default=0)),
                ('critico', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salud', models.IntegerField(default=200)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.arma')),
            ],
        ),
    ]
