# Generated by Django 5.1.5 on 2025-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='critico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arma',
            name='dano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='salud',
            field=models.IntegerField(),
        ),
    ]
