# Generated by Django 5.1.5 on 2025-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salud', models.IntegerField(default=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='arma',
            name='potencia',
        ),
        migrations.AddField(
            model_name='arma',
            name='critico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arma',
            name='dano',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arma',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Personaje',
        ),
    ]
