# Generated by Django 5.1.5 on 2025-02-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_remove_arma_potencia_arma_critico_arma_dano_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Personaje',
        ),
    ]
