# Generated by Django 5.1.6 on 2025-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_personaje_arma_combate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='mana',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='salud',
            field=models.IntegerField(default=200),
        ),
    ]
