# Generated by Django 5.1.5 on 2025-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personaje_mana_alter_personaje_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='turnos',
            field=models.IntegerField(default=0),
        ),
    ]
